---
description: Pipeline for UniFi IPS/IDS events
processors:
  - set:
      field: ecs.version
      value: "8.11.0"
  - set:
      field: event.kind
      value: alert
  - set:
      field: event.category
      value: intrusion_detection
  - set:
      field: event.type
      value: denied
  - remove:
      field: source.ip
      if: "ctx?.source?.ip == ''"
      ignore_missing: true
  - remove:
      field: destination.ip
      if: "ctx?.destination?.ip == ''"
      ignore_missing: true
  - convert:
      field: source.ip
      type: ip
      ignore_missing: true
      ignore_failure: true
  - convert:
      field: destination.ip
      type: ip
      ignore_missing: true
      ignore_failure: true
  - convert:
      field: source.port
      type: integer
      ignore_missing: true
      ignore_failure: true
  - convert:
      field: destination.port
      type: integer
      ignore_missing: true
      ignore_failure: true
on_failure:
  - append:
      field: error.message
      value: >-
        Processor {{ _ingest.on_failure_processor_type }} (tag:
        {{ _ingest.on_failure_processor_tag }}) failed with message:
        {{ _ingest.on_failure_message }}
  - set:
      field: event.kind
      value: pipeline_error
