---
description: Pipeline for UniFi network/VLAN configuration snapshot
processors:
  - set:
      field: ecs.version
      value: "8.11.0"
  - set:
      field: event.kind
      value: state
  - set:
      field: event.type
      value: info
  - remove:
      field: unifi.network.ip_subnet
      if: "ctx.unifi?.network?.ip_subnet == ''"
      ignore_missing: true
  - remove:
      field: unifi.network.dhcpd_start
      if: "ctx.unifi?.network?.dhcpd_start == ''"
      ignore_missing: true
  - remove:
      field: unifi.network.dhcpd_stop
      if: "ctx.unifi?.network?.dhcpd_stop == ''"
      ignore_missing: true
on_failure:
  - append:
      field: error.message
      value: >-
        Processor {{ _ingest.on_failure_processor_type }} (tag:
        {{ _ingest.on_failure_processor_tag }}) failed with message:
        {{ _ingest.on_failure_message }}
  - set:
      field: event.kind
      value: pipeline_error
